// Mock data for the interior design app

export const TRENDING_STYLES = [
  {
    id: '1',
    name: 'Modern Luxury',
    tag: 'TRENDING',
    description: 'Sleek lines with opulent finishes',
    color: '#6C47FF',
    gradient: ['#6C47FF', '#A855F7'],
    emoji: '✨',
    projectCount: '12.4K',
    matchScore: 98,
  },
  {
    id: '2',
    name: 'Japandi',
    tag: 'HOT',
    description: 'Japanese-Scandinavian harmony',
    color: '#00D4AA',
    gradient: ['#00D4AA', '#0099FF'],
    emoji: '🌿',
    projectCount: '8.7K',
    matchScore: 95,
  },
  {
    id: '3',
    name: 'Minimalist',
    tag: 'POPULAR',
    description: 'Less is more, beautifully',
    color: '#F5A623',
    gradient: ['#F5A623', '#FF6B6B'],
    emoji: '◻️',
    projectCount: '19.2K',
    matchScore: 92,
  },
  {
    id: '4',
    name: 'Scandinavian',
    tag: 'NEW',
    description: 'Nordic warmth and simplicity',
    color: '#FF6B6B',
    gradient: ['#FF6B6B', '#FF4D8D'],
    emoji: '🏔️',
    projectCount: '6.1K',
    matchScore: 88,
  },
];

export const STYLE_CATEGORIES = [
  {
    id: 'modern',
    name: 'Modern',
    description: 'Clean lines, open spaces, neutral palettes',
    emoji: '🏙️',
    gradient: ['#6C47FF', '#A855F7'],
    tags: ['Contemporary', 'Open Plan', 'Neutral'],
    featured: true,
  },
  {
    id: 'luxury',
    name: 'Luxury',
    description: 'Opulent materials, rich textures, gold accents',
    emoji: '👑',
    gradient: ['#F5A623', '#FF6B6B'],
    tags: ['Gold Accents', 'Marble', 'Premium'],
    featured: true,
  },
  {
    id: 'scandinavian',
    name: 'Scandinavian',
    description: 'Hygge vibes, wood tones, cozy layers',
    emoji: '🌲',
    gradient: ['#00D4AA', '#0099FF'],
    tags: ['Wood', 'Hygge', 'Natural Light'],
    featured: false,
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Functional beauty with purposeful restraint',
    emoji: '⬜',
    gradient: ['#64748B', '#334155'],
    tags: ['Clean', 'Functional', 'White Space'],
    featured: false,
  },
  {
    id: 'industrial',
    name: 'Industrial',
    description: 'Raw materials, exposed structures, urban edge',
    emoji: '🏭',
    gradient: ['#475569', '#1E293B'],
    tags: ['Exposed Brick', 'Metal', 'Raw'],
    featured: false,
  },
  {
    id: 'japandi',
    name: 'Japandi',
    description: 'Wabi-sabi meets Nordic calm and function',
    emoji: '🌿',
    gradient: ['#059669', '#0284C7'],
    tags: ['Wabi-sabi', 'Natural', 'Zen'],
    featured: true,
  },
  {
    id: 'indian',
    name: 'Indian Traditional',
    description: 'Vibrant colors, intricate patterns, heritage art',
    emoji: '🏛️',
    gradient: ['#DC2626', '#D97706'],
    tags: ['Vibrant', 'Heritage', 'Artisan'],
    featured: false,
  },
  {
    id: 'boho',
    name: 'Bohemian',
    description: 'Eclectic layers, global textiles, free spirit',
    emoji: '🌺',
    gradient: ['#9333EA', '#EC4899'],
    tags: ['Eclectic', 'Global', 'Textiles'],
    featured: false,
  },
];

export const RECENT_PROJECTS = [
  {
    id: '1',
    name: 'Master Bedroom',
    style: 'Modern Luxury',
    date: '2 days ago',
    status: 'completed',
    beforeColor: '#C8B89A',
    afterGradient: ['#6C47FF', '#A855F7'],
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Living Room',
    style: 'Japandi',
    date: '5 days ago',
    status: 'completed',
    beforeColor: '#B0C4B1',
    afterGradient: ['#00D4AA', '#0099FF'],
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Kitchen Makeover',
    style: 'Minimalist',
    date: '1 week ago',
    status: 'draft',
    beforeColor: '#D4C5A9',
    afterGradient: ['#F5A623', '#FF6B6B'],
    rating: 4.7,
  },
];

export const DESIGN_IDEAS = [
  {
    id: '1',
    title: 'Floating Shelves Paradise',
    likes: '24.5K',
    category: 'Living Room',
    gradient: ['#6C47FF', '#A855F7'],
    premium: false,
  },
  {
    id: '2',
    title: 'Marble Kitchen Dreams',
    likes: '18.2K',
    category: 'Kitchen',
    gradient: ['#F5A623', '#FF6B6B'],
    premium: true,
  },
  {
    id: '3',
    title: 'Cozy Reading Nook',
    likes: '31.7K',
    category: 'Study',
    gradient: ['#00D4AA', '#0099FF'],
    premium: false,
  },
  {
    id: '4',
    title: 'Spa Bathroom Oasis',
    likes: '15.9K',
    category: 'Bathroom',
    gradient: ['#9333EA', '#EC4899'],
    premium: true,
  },
];

export const MARKETPLACE_DESIGNERS = [
  {
    id: '1',
    name: 'Priya Sharma',
    specialty: 'Modern & Luxury',
    rating: 4.9,
    reviews: 342,
    price: '₹15,000',
    verified: true,
    badge: '🏆 Top Designer',
    gradient: ['#6C47FF', '#A855F7'],
    projects: 89,
    available: true,
  },
  {
    id: '2',
    name: 'Arjun Mehta',
    specialty: 'Scandinavian',
    rating: 4.8,
    reviews: 218,
    price: '₹12,000',
    verified: true,
    badge: '⭐ Featured',
    gradient: ['#00D4AA', '#0099FF'],
    projects: 64,
    available: true,
  },
  {
    id: '3',
    name: 'Kavya Nair',
    specialty: 'Indian Traditional',
    rating: 4.9,
    reviews: 497,
    price: '₹18,000',
    verified: true,
    badge: '🎯 Best Value',
    gradient: ['#DC2626', '#D97706'],
    projects: 143,
    available: false,
  },
];

export const MARKETPLACE_FURNITURE = [
  {
    id: '1',
    name: 'IKEA',
    category: 'Furniture & Decor',
    rating: 4.7,
    orders: '50K+',
    badge: 'Partner',
    discount: '15% OFF',
    gradient: ['#0057A8', '#00A8E8'],
  },
  {
    id: '2',
    name: 'Urban Ladder',
    category: 'Premium Furniture',
    rating: 4.8,
    orders: '32K+',
    badge: 'Premium',
    discount: '20% OFF',
    gradient: ['#8B4513', '#D2691E'],
  },
  {
    id: '3',
    name: 'Pepperfry',
    category: 'Home Decor',
    rating: 4.6,
    orders: '45K+',
    badge: 'Featured',
    discount: '25% OFF',
    gradient: ['#FF6B6B', '#FF4D8D'],
  },
];

export const SUBSCRIPTION_PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: '₹0',
    period: 'Forever',
    features: [
      '3 AI generations/month',
      '5 style templates',
      'Basic export',
      'Community access',
    ],
    cta: 'Current Plan',
    popular: false,
    gradient: ['#9B96B0', '#5A5175'],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: '₹999',
    period: '/month',
    features: [
      'Unlimited AI generations',
      '50+ style templates',
      'HD export & share',
      'Before/After slider',
      'Priority support',
      '3D room preview',
    ],
    cta: 'Upgrade to Pro',
    popular: true,
    gradient: ['#6C47FF', '#A855F7'],
  },
  {
    id: 'studio',
    name: 'Studio',
    price: '₹2,499',
    period: '/month',
    features: [
      'Everything in Pro',
      'Client collaboration',
      'Commercial license',
      'API access',
      'Dedicated designer',
      'White-label export',
    ],
    cta: 'Go Studio',
    popular: false,
    gradient: ['#F5A623', '#FF6B6B'],
  },
];
